DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS houses;

CREATE TABLE houses(
  id SERIAL8 PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  emblem VARCHAR(255)
);

CREATE TABLE students(
  id SERIAL8 PRIMARY KEY,
  first_name VARCHAR(255) NOT NULL,
  second_name VARCHAR(255) NOT NULL,
  house_id INT8 REFERENCES houses(id) ON DELETE CASCADE,
  age INT8
);
